"""initial

Revision ID: 21f920be33f4
Revises: 
Create Date: 2022-09-09 20:29:59.329114

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '21f920be33f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_items',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.Column('parent_id', sa.String(), nullable=True),
                    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id', 'date')
                    )
    op.create_table('item_tree_paths',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('ancestor_id', sa.String(), nullable=False),
                    sa.Column('ancestor_date', sa.DateTime(), nullable=False),
                    sa.Column('descendant_id', sa.String(), nullable=False),
                    sa.Column('descendant_date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['ancestor_id', 'ancestor_date'],
                                            ['system_items.id', 'system_items.date'], ),
                    sa.ForeignKeyConstraint(['descendant_id', 'descendant_date'],
                                            ['system_items.id', 'system_items.date'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tree_paths')
    op.drop_table('system_items')
    # ### end Alembic commands ###
