"""initial migration

Revision ID: 280c8578c10c
Revises: 
Create Date: 2022-09-13 17:06:45.303005

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '280c8578c10c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_item_links',
                    sa.Column('parent_id', sa.String(), nullable=False),
                    sa.Column('child_id', sa.String(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('depth', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('parent_id', 'child_id', 'date', name=op.f('pk__system_item_links'))
                    )
    op.create_table('system_item_type_registry',
                    sa.Column('system_item_id', sa.String(), nullable=False),
                    sa.Column('system_item_type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
                    sa.PrimaryKeyConstraint('system_item_id', name=op.f('pk__system_item_type_registry'))
                    )
    # noinspection PyTypeChecker
    op.create_table('system_items',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('parent_id', sa.String(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['system_item_type_registry.system_item_id'],
                                            name=op.f('fk__system_items__parent_id__system_item_type_registry')),
                    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk__system_items'))
                    )
    op.execute("""
CREATE FUNCTION check_type_change() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.type <> NEW.type THEN
        RAISE EXCEPTION 'system_items.type field is immutable'; 
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER type_update_trigger BEFORE UPDATE ON system_items FOR EACH ROW
      EXECUTE PROCEDURE check_type_change();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_items')
    op.drop_table('system_item_type_registry')
    op.drop_table('system_item_links')
    # ### end Alembic commands ###
