"""initial migration

Revision ID: 59a055fdea51
Revises: 
Create Date: 2022-09-13 13:42:59.126195

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '59a055fdea51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_item_type_registry',
                    sa.Column('system_item_id', sa.String(), nullable=False),
                    sa.Column('system_item_type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
                    sa.PrimaryKeyConstraint('system_item_id', name=op.f('pk__system_item_type_registry'))
                    )
    op.create_table('system_items',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('parent_id', sa.String(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk__system_items'))
                    )
    # noinspection PyTypeChecker
    op.create_table('system_item_links',
                    sa.Column('parent_id', sa.String(), nullable=False),
                    sa.Column('child_id', sa.String(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('depth', sa.Integer(), server_default='1', nullable=False),
                    sa.ForeignKeyConstraint(['child_id', 'date'], ['system_items.id', 'system_items.date'],
                                            name=op.f('fk__system_item_links__child_id_date__system_items'),
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['parent_id', 'date'], ['system_items.id', 'system_items.date'],
                                            name=op.f('fk__system_item_links__parent_id_date__system_items'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('parent_id', 'child_id', 'date', name=op.f('pk__system_item_links'))
                    )
    op.execute("""
CREATE FUNCTION check_type_change() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.system_item_type <> NEW.system_item_type THEN
        RAISE EXCEPTION 'system_item_type field is immutable'; 
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER type_update_trigger BEFORE UPDATE ON system_item_type_registry FOR EACH ROW
      EXECUTE PROCEDURE check_type_change();
            """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_item_links')
    op.drop_table('system_items')
    op.drop_table('system_item_type_registry')
    # ### end Alembic commands ###
