"""initial migration

Revision ID: 9007e7c477d9
Revises: 
Create Date: 2022-09-14 15:00:16.738566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9007e7c477d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_item_links',
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', 'date', name=op.f('pk__system_item_links'))
    )
    op.create_table('system_item_type_registry',
    sa.Column('system_item_id', sa.String(), nullable=False),
    sa.Column('system_item_type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
    sa.PrimaryKeyConstraint('system_item_id', name=op.f('pk__system_item_type_registry'))
    )
    op.create_table('system_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['system_item_type_registry.system_item_id'], name=op.f('fk__system_items__parent_id__system_item_type_registry')),
    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk__system_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_items')
    op.drop_table('system_item_type_registry')
    op.drop_table('system_item_links')
    # ### end Alembic commands ###
