"""initial migration

Revision ID: ca543178e033
Revises: 
Create Date: 2022-09-13 09:33:48.900257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca543178e033'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk__system_items'))
    )
    op.create_table('system_item_links',
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('depth', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['child_id', 'date'], ['system_items.id', 'system_items.date'], name=op.f('fk__system_item_links__child_id_date__system_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id', 'date'], ['system_items.id', 'system_items.date'], name=op.f('fk__system_item_links__parent_id_date__system_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', 'date', name=op.f('pk__system_item_links'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_item_links')
    op.drop_table('system_items')
    # ### end Alembic commands ###
