"""initial migration

Revision ID: daa36032e640
Revises: 
Create Date: 2022-09-09 20:51:41.171373

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'daa36032e640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_items',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.Column('parent_id', sa.String(), nullable=True),
                    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='systemitemtype'), nullable=False),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id', 'date', name=op.f('pk__system_items'))
                    )
    op.create_table('item_tree_paths',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('ancestor_id', sa.String(), nullable=False),
                    sa.Column('ancestor_date', sa.DateTime(), nullable=False),
                    sa.Column('descendant_id', sa.String(), nullable=False),
                    sa.Column('descendant_date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['ancestor_id', 'ancestor_date'], ['system_items.id', 'system_items.date'],
                                            name=op.f('fk__item_tree_paths__ancestor_id_ancestor_date__system_items')),
                    sa.ForeignKeyConstraint(['descendant_id', 'descendant_date'],
                                            ['system_items.id', 'system_items.date'], name=op.f(
                            'fk__item_tree_paths__descendant_id_descendant_date__system_items')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__item_tree_paths'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tree_paths')
    op.drop_table('system_items')
    # ### end Alembic commands ###
