version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=yadisk_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dbvolume:/var/lib/postgresql/data
    restart: always

  yadisk-api:
    image: snowborodist/yadisk-api:1.0.0
    environment:
      - database_url=postgresql+asyncpg://postgres:postgres@postgres:5432/yadisk_db
    ports:
      - "80:5000"
    depends_on:
      - postgres
    restart: always

volumes:
  dbvolume: